require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe HackathonsController do

  def mock_hackathon(stubs={})
    @mock_hackathon ||= mock_model(Hackathon, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all hackathons as @hackathons" do
      Hackathon.stub(:all) { [mock_hackathon] }
      get :index
      assigns(:hackathons).should eq([mock_hackathon])
    end
  end

  describe "GET show" do
    it "assigns the requested hackathon as @hackathon" do
      Hackathon.stub(:find).with("37") { mock_hackathon }
      get :show, :id => "37"
      assigns(:hackathon).should be(mock_hackathon)
    end
  end

  describe "GET new" do
    it "assigns a new hackathon as @hackathon" do
      Hackathon.stub(:new) { mock_hackathon }
      get :new
      assigns(:hackathon).should be(mock_hackathon)
    end
  end

  describe "GET edit" do
    it "assigns the requested hackathon as @hackathon" do
      Hackathon.stub(:find).with("37") { mock_hackathon }
      get :edit, :id => "37"
      assigns(:hackathon).should be(mock_hackathon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created hackathon as @hackathon" do
        Hackathon.stub(:new).with({'these' => 'params'}) { mock_hackathon(:save => true) }
        post :create, :hackathon => {'these' => 'params'}
        assigns(:hackathon).should be(mock_hackathon)
      end

      it "redirects to the created hackathon" do
        Hackathon.stub(:new) { mock_hackathon(:save => true) }
        post :create, :hackathon => {}
        response.should redirect_to(hackathon_url(mock_hackathon))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hackathon as @hackathon" do
        Hackathon.stub(:new).with({'these' => 'params'}) { mock_hackathon(:save => false) }
        post :create, :hackathon => {'these' => 'params'}
        assigns(:hackathon).should be(mock_hackathon)
      end

      it "re-renders the 'new' template" do
        Hackathon.stub(:new) { mock_hackathon(:save => false) }
        post :create, :hackathon => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hackathon" do
        Hackathon.stub(:find).with("37") { mock_hackathon }
        mock_hackathon.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :hackathon => {'these' => 'params'}
      end

      it "assigns the requested hackathon as @hackathon" do
        Hackathon.stub(:find) { mock_hackathon(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:hackathon).should be(mock_hackathon)
      end

      it "redirects to the hackathon" do
        Hackathon.stub(:find) { mock_hackathon(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(hackathon_url(mock_hackathon))
      end
    end

    describe "with invalid params" do
      it "assigns the hackathon as @hackathon" do
        Hackathon.stub(:find) { mock_hackathon(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:hackathon).should be(mock_hackathon)
      end

      it "re-renders the 'edit' template" do
        Hackathon.stub(:find) { mock_hackathon(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hackathon" do
      Hackathon.stub(:find).with("37") { mock_hackathon }
      mock_hackathon.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the hackathons list" do
      Hackathon.stub(:find) { mock_hackathon }
      delete :destroy, :id => "1"
      response.should redirect_to(hackathons_url)
    end
  end

end
