require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe InviteRequestsController do

  def mock_invite_request(stubs={})
    @mock_invite_request ||= mock_model(InviteRequest, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all invite_requests as @invite_requests" do
      InviteRequest.stub(:all) { [mock_invite_request] }
      get :index
      assigns(:invite_requests).should eq([mock_invite_request])
    end
  end

  describe "GET show" do
    it "assigns the requested invite_request as @invite_request" do
      InviteRequest.stub(:find).with("37") { mock_invite_request }
      get :show, :id => "37"
      assigns(:invite_request).should be(mock_invite_request)
    end
  end

  describe "GET new" do
    it "assigns a new invite_request as @invite_request" do
      InviteRequest.stub(:new) { mock_invite_request }
      get :new
      assigns(:invite_request).should be(mock_invite_request)
    end
  end

  describe "GET edit" do
    it "assigns the requested invite_request as @invite_request" do
      InviteRequest.stub(:find).with("37") { mock_invite_request }
      get :edit, :id => "37"
      assigns(:invite_request).should be(mock_invite_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created invite_request as @invite_request" do
        InviteRequest.stub(:new).with({'these' => 'params'}) { mock_invite_request(:save => true) }
        post :create, :invite_request => {'these' => 'params'}
        assigns(:invite_request).should be(mock_invite_request)
      end

      it "redirects to the created invite_request" do
        InviteRequest.stub(:new) { mock_invite_request(:save => true) }
        post :create, :invite_request => {}
        response.should redirect_to(invite_request_url(mock_invite_request))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invite_request as @invite_request" do
        InviteRequest.stub(:new).with({'these' => 'params'}) { mock_invite_request(:save => false) }
        post :create, :invite_request => {'these' => 'params'}
        assigns(:invite_request).should be(mock_invite_request)
      end

      it "re-renders the 'new' template" do
        InviteRequest.stub(:new) { mock_invite_request(:save => false) }
        post :create, :invite_request => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invite_request" do
        InviteRequest.stub(:find).with("37") { mock_invite_request }
        mock_invite_request.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :invite_request => {'these' => 'params'}
      end

      it "assigns the requested invite_request as @invite_request" do
        InviteRequest.stub(:find) { mock_invite_request(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:invite_request).should be(mock_invite_request)
      end

      it "redirects to the invite_request" do
        InviteRequest.stub(:find) { mock_invite_request(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(invite_request_url(mock_invite_request))
      end
    end

    describe "with invalid params" do
      it "assigns the invite_request as @invite_request" do
        InviteRequest.stub(:find) { mock_invite_request(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:invite_request).should be(mock_invite_request)
      end

      it "re-renders the 'edit' template" do
        InviteRequest.stub(:find) { mock_invite_request(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invite_request" do
      InviteRequest.stub(:find).with("37") { mock_invite_request }
      mock_invite_request.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the invite_requests list" do
      InviteRequest.stub(:find) { mock_invite_request }
      delete :destroy, :id => "1"
      response.should redirect_to(invite_requests_url)
    end
  end

end
