require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe TeamMembershipsController do

  def mock_team_membership(stubs={})
    @mock_team_membership ||= mock_model(TeamMembership, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all team_memberships as @team_memberships" do
      TeamMembership.stub(:all) { [mock_team_membership] }
      get :index
      assigns(:team_memberships).should eq([mock_team_membership])
    end
  end

  describe "GET show" do
    it "assigns the requested team_membership as @team_membership" do
      TeamMembership.stub(:find).with("37") { mock_team_membership }
      get :show, :id => "37"
      assigns(:team_membership).should be(mock_team_membership)
    end
  end

  describe "GET new" do
    it "assigns a new team_membership as @team_membership" do
      TeamMembership.stub(:new) { mock_team_membership }
      get :new
      assigns(:team_membership).should be(mock_team_membership)
    end
  end

  describe "GET edit" do
    it "assigns the requested team_membership as @team_membership" do
      TeamMembership.stub(:find).with("37") { mock_team_membership }
      get :edit, :id => "37"
      assigns(:team_membership).should be(mock_team_membership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created team_membership as @team_membership" do
        TeamMembership.stub(:new).with({'these' => 'params'}) { mock_team_membership(:save => true) }
        post :create, :team_membership => {'these' => 'params'}
        assigns(:team_membership).should be(mock_team_membership)
      end

      it "redirects to the created team_membership" do
        TeamMembership.stub(:new) { mock_team_membership(:save => true) }
        post :create, :team_membership => {}
        response.should redirect_to(team_membership_url(mock_team_membership))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved team_membership as @team_membership" do
        TeamMembership.stub(:new).with({'these' => 'params'}) { mock_team_membership(:save => false) }
        post :create, :team_membership => {'these' => 'params'}
        assigns(:team_membership).should be(mock_team_membership)
      end

      it "re-renders the 'new' template" do
        TeamMembership.stub(:new) { mock_team_membership(:save => false) }
        post :create, :team_membership => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested team_membership" do
        TeamMembership.stub(:find).with("37") { mock_team_membership }
        mock_team_membership.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :team_membership => {'these' => 'params'}
      end

      it "assigns the requested team_membership as @team_membership" do
        TeamMembership.stub(:find) { mock_team_membership(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:team_membership).should be(mock_team_membership)
      end

      it "redirects to the team_membership" do
        TeamMembership.stub(:find) { mock_team_membership(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(team_membership_url(mock_team_membership))
      end
    end

    describe "with invalid params" do
      it "assigns the team_membership as @team_membership" do
        TeamMembership.stub(:find) { mock_team_membership(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:team_membership).should be(mock_team_membership)
      end

      it "re-renders the 'edit' template" do
        TeamMembership.stub(:find) { mock_team_membership(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested team_membership" do
      TeamMembership.stub(:find).with("37") { mock_team_membership }
      mock_team_membership.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the team_memberships list" do
      TeamMembership.stub(:find) { mock_team_membership }
      delete :destroy, :id => "1"
      response.should redirect_to(team_memberships_url)
    end
  end

end
